info/__init__.py
from flask import Flask
from config import configs
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy
from redis import StrictRedis
from flask_wtf import CSRFProtect, csrf
from logging.handlers import RotatingFileHandler
import logging

from pymysql import install_as_MySQLdb

install_as_MySQLdb()


db = SQLAlchemy()
redis_store = None


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(configs[config_name])

    db.init_app(app)

    global redis_store

    redis_store = StrictRedis(configs[config_name].REDIS_HOST, configs[config_name].REDIS_PORT)

    Session(app)

    CSRFProtect(app)

    # 生成 CSRF_token
    @app.after_request
    def after_request(response):
        csrf_token = csrf.generate_csrf()
        response.set_cookie("csrf_token", csrf_token)
        return response

    from info.news import news_blue
    app.register_blueprint(news_blue)
    from info.passport import passport_blue
    app.register_blueprint(passport_blue)
    from info.user import user_blue
    app.register_blueprint(user_blue)

    # 开启日志
    create_log(config_name)

    # 添加过滤器
    from info.comment import rank
    app.add_template_filter(rank)

    return app


def create_log(config_name):
    logging.basicConfig(level=configs[config_name].LOGGING_DEBUG)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)

info/news/__init__.py
from flask import Blueprint

news_blue = Blueprint("news", __name__)

from . import views

info/news/views.py
from . import news_blue
from flask import render_template, session, g, request, current_app, abort, jsonify
from info.comment import user_model
from info.utils import models
from info.utils import constants
from info.utils.response_code import RET
from sqlalchemy import and_
from info import db
import datetime


# 关注用户
@news_blue.route("/follow", methods=["POST"])
@user_model
def follow():
    user = g.user

    if not user:
        return jsonify(errno=RET.NODATA, errmsg="用户未登录")

    author_id = request.json.get("author_id")
    action = request.json.get('action')

    # 需要区分关注者和被关注者
    # 自己 关注 , 发布的 被关注
    # user.id    author_id
    # 用户的所有粉丝 followers
    print(author_id, user.id)
    try:
        author = models.User.query.get(author_id)

        author_fans = author.followers

    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库中没有")

    if not author:
        return jsonify(errno=RET.NODATA, errmsg="作者未查询到")

    # 查询 目前的用户是否关注了 此作者
    fans_list = [fans.id for fans in author_fans]

    print(fans_list)

    try:
        if action == 'fo':
            author.followers.append(user)
            msg = "关注成功"
        else:
            if user.id in fans_list:
                author.followers.remove(user)
                msg = '取消关注'
            else:
                msg = '未关注'
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库添加关注失败")

    return jsonify(errno=RET.OK, errmsg=msg)


# 点赞和取消赞
@news_blue.route("/liked", methods=["POST"])
@user_model
def liked():
    user = g.user

    if not user:
        return jsonify(errno=RET.NODATA, errmsg="用户未登录")

    action = request.json.get("action")

    comment_id = request.json.get("comment_id")

    if action not in ["liked", "unlike"]:
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

    try:
        comments_object = models.Comment.query.filter(models.Comment.id == comment_id).first()
        com_like = models.CommentLike.query.filter(and_(models.CommentLike.comment_id == comment_id,
                                                        models.CommentLike.user_id == user.id)).first()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库查询错误")

    if action == "unlike":
        comments_object.like_count -= 1

        try:
            db.session.delete(com_like)
            db.session.commit()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库删除错误")

        msg = "取消点赞成功"

    else:
        comment_like = models.CommentLike()
        comment_like.create_time = datetime.datetime.now()
        comment_like.comment_id = comment_id
        comment_like.user_id = user.id

        comments_object.like_count += 1

        try:
            db.session.add(comment_like)
            db.session.commit()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库添加错误")

        msg = "点赞成功"

    return jsonify(errno=RET.OK, errmsg=msg, liked=comments_object.like_count)


# 评论
@news_blue.route("/comments", methods=["POST"])
@user_model
def comments():
    # 评论有有两种form表单框 1. 用户评论新闻 2. 用户评论用户
    # 需要: 新闻id 用户id 表单内容 父id

    user = g.user

    news_id = request.json.get("news_id")

    content = request.json.get("content")

    parent_id = request.json.get("parent_id")

    if not news_id:
        return jsonify(errno=RET.NODATA, errmsg="新闻不存在")

    if not content:
        return jsonify(errno=RET.NODATA, errmsg="请输入内容")

    if not user:
        return jsonify(errno=RET.NODATA, errmsg="用户不存在")

    # 保存评论 (评论新闻)
    comment = models.Comment()
    comment.content = content
    comment.user_id = user.id
    comment.news_id = news_id
    comment.create_time = datetime.datetime.now()

    if parent_id:

        print(parent_id, "-----")

        comment.parent_id = parent_id

    try:
        db.session.add(comment)
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据无法保存")

    print(comment)

    params = {
        "user": user.to_dict(),
        "comment": comment.to_dict()
    }

    return jsonify(errno=RET.OK, errmsg="评论成功", data=params)


# 新闻收藏
@news_blue.route("/collection", methods=["GET"])
@user_model
def collection():
    user = g.user

    if not user:
        return jsonify(errno=RET.NODATA, errmsg="用户未登录")

    action = request.args.get("action")

    cur_news_id = request.args.get("news_id")

    if not all([action, cur_news_id]):
        return jsonify(errno=RET.NODATA, errmsg="参数不完整")

    # 查看是否已经进行收藏
    try:
        news_collected = user.collection_news.all()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库查询信息错误")

    news_id_list = [news.id for news in news_collected]

    print(news_id_list, cur_news_id)

    if action not in ["collection", "collected"]:
        return jsonify(errno=RET.DATAERR, errmsg="类型错误")

    news = models.News.query.get(cur_news_id)

    if action == "collection":  # 进行收藏
        # 多对多的收藏
        user.collection_news.append(news)
        msg = "收藏成功"
    else:
        user.collection_news.remove(news)
        msg = "取消成功"

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库操作错误")

    return jsonify(errno=RET.OK, errmsg=msg)


# 实现新闻详情页的显示
@news_blue.route("/detail/<int:num_id>", methods=["GET"])
@user_model
def detail(num_id):
    user = g.user

    # 根据id 查询新闻详情
    try:
        news = models.News.query.get(num_id)
        # 点击排行的查询
        news_list = models.News.query.order_by(models.News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="新闻查询错误")

    if not news:
        return jsonify(errno=RET.NODATA, errmsg="新闻不存在")

    is_collected = False

    is_followed = False

    list_comment_id = []

    if user:
        # 优化收藏, 判断当前用户是否收藏了此新闻
        try:
            news_collected = user.collection_news.all()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库查询信息错误")

        news_id_list = [news.id for news in news_collected]

        print(num_id, news_id_list)

        if num_id in news_id_list:
            is_collected = True

        # 判断当前用户是否对此评论点赞
        # 1. 获取全部点赞的评论 2. 判断
        all_comments = None
        try:
            all_comments = models.CommentLike.query.filter(models.CommentLike.user_id == user.id).all()
        except Exception as e:
            current_app.logger.error(e)

        #  # 1. 获取全部点赞的评论
        list_comment_id = [value.comment_id for value in all_comments]

        # 判断是否关注
        news_detail = news.to_dict()
        print(news_detail)
        author_id = news_detail["author"]['id']

        try:
            author = models.User.query.get(author_id)
            author_fans = author.followers
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库错误")

        fans_list = [fans.id for fans in author_fans]

        if user.id in fans_list:
            is_followed = True

    # 显示评论
    try:
        news_comments = models.Comment.query.order_by(models.Comment.create_time.desc()).\
            filter(models.Comment.news_id == num_id).all()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库查询信息错误")

    news_comments = [comments_object.to_dict() for comments_object in news_comments]

    # 添加一个判断是否点赞的字段
    for comments_current in news_comments:
        comments_current["is_liked"] = False
        if comments_current["id"] in list_comment_id:
            comments_current["is_liked"] = True

    context = {
        "user": user,
        "news": news_list,
        "detail_news": news.to_dict(),
        "is_collected": is_collected,
        'is_followed': is_followed,
        "news_comments": news_comments
    }

    return render_template("html/detail.html", context=context)


# 首页显示新闻, 实现滑动翻页
@news_blue.route("/news_all", methods=["GET"])
def news_all():
    paginate = None
    # 当前种类
    current_id = request.args.get("cid", 1)
    # 当前页
    cur_page = request.args.get("page", 1)

    print(current_id, cur_page)

    if not all([current_id, cur_page]):
        abort(404)

    try:
        current_id = int(current_id)
        cur_page = int(cur_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="数据转化失败")

    try:
        if current_id == 1:
            paginate = models.News.query.order_by(models.News.create_time.desc()).\
                paginate(cur_page, constants.HOME_PAGE_MAX_NEWS, False)
            print(paginate)
        else:
            paginate = models.News.query.filter(models.News.category_id == current_id)\
                .order_by(models.News.create_time.desc()). \
                paginate(cur_page, constants.HOME_PAGE_MAX_NEWS, False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库查询失败")

    objects_news = paginate.items
    total_page = paginate.pages
    current_page = paginate.page

    news_list = []

    for news in objects_news:
        news_list.append(news.to_dict())

    context = {
        "news": news_list,
        "tpage": total_page,
        "cpage": current_page
    }

    return jsonify(errno=RET.OK, context=context, errmsg="成功")


@news_blue.route("/")
@user_model
def index():

    user = g.user

    # 根据click 进行排序
    try:

info/passport/__init__.py
from flask import Blueprint

passport_blue = Blueprint("passport", __name__, url_prefix="/passport")

from . import views

info/passport/views.py
from . import passport_blue
from info.utils.captcha.captcha import captcha
from flask import request, jsonify, abort, make_response, current_app, session
from info import redis_store
from info.utils.response_code import RET
from info.utils.yuntongxun import sms
from info.utils import constants, models
import random
import re
import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from info import db


@passport_blue.route("/logout")
def logout():
    session.pop("uid")

    if session.get("uid"):
        return jsonify(errno=RET.PARAMERR, errmsg="退出失败")

    return jsonify(errno=RET.OK, errmsg="退出")


# 登录
@passport_blue.route("/login", methods=["POST"])
def login():
    # 手机号 密码
    mobile = request.json.get("mobile")

    pwd = request.json.get("password")

    if not all([mobile, pwd]):
        return jsonify(errno=RET.NODATA, errmsg="信息填写不完整")

    # 匹配手机号
    if not re.match(r"^1[356789]\d{9}$", mobile):
        return jsonify(errno=RET.PARAMERR, errmsg="手机号填写不正确")

    try:
        user = models.User.query.filter(models.User.mobile == mobile).first()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="用户信息查询不到")

    if not user:
        return jsonify(errno=RET.NODATA, errmsg="该用户不存在")

    # 比较密码 -- 返回 true 或 false
    result = check_password_hash(user.password_hash, pwd)

    if not result:
        return jsonify(errno=RET.PARAMERR, errmsg="手机号或者密码错误")

    session["uid"] = user.id

    return jsonify(errno=RET.OK, errmsg="登录成功")


# 注册
@passport_blue.route("/register", methods=["POST"])
def register():
    if request.method == "POST":
        # 得到 手机号 短信验证码 密码
        mobile = request.json.get("mobile")

        sms_num = request.json.get("smscode")

        pwd = request.json.get("password")

        if not all([mobile, sms_num, pwd]):
            return jsonify(errno=RET.NODATA, errmsg="信息填写不完整")

        # 匹配手机号
        if not re.match(r"^1[356789]\d{9}$", mobile):
            return jsonify(errno=RET.PARAMERR, errmsg="手机号填写不正确")

        # 验证短信验证码
        try:
            code = redis_store.get("smsCode:"+mobile)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="无法获取数据")

        if not code:
            return jsonify(errno=RET.NODATA, errmsg="短信验证码失效")

        if code.decode() != sms_num:
            return jsonify(errno=RET.PARAMERR, errmsg="短信验证码填写不正确")

        # 密码加密
        password_hs = generate_password_hash(pwd)

        user = models.User()
        user.nick_name = mobile
        user.create_time = datetime.datetime.now()
        user.password_hash = password_hs
        user.mobile = mobile

        try:
            db.session.add(user)
            db.session.commit()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="用户注册失败")

        return jsonify(errno=RET.OK, errmsg="用户注册成功")


# 短信验证码生成
@passport_blue.route("/sms_code", methods=["POST"])
def sms_code():

    if request.method == "POST":
        # 得到 手机号 图片验证码和UUID 短信验证码的生成和保存
        mobile = request.json.get("mobile")

        pic_code = request.json.get("image_code")

        uuid = request.json.get("image_code_id")

        if not all([mobile, pic_code, uuid]):
            return jsonify(errno=RET.NODATA, errmsg="信息填写不完整")

        # 匹配手机号
        if not re.match(r"^1[356789]\d{9}$", mobile):
            return jsonify(errno=RET.PARAMERR, errmsg="手机号填写不正确")

        try:
            code = redis_store.get("imageCode:"+uuid)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="服务器无法获取数据")

        if not code:
            return jsonify(errno=RET.NODATA, errmsg="图片验证码失效")

        print(code, pic_code)

        if code.decode().lower() != pic_code.lower():
            return jsonify(errno=RET.DATAERR, errmsg="图片验证码填写错误")

        # 生成短信验证码
        num = random.randint(1, 999999)

        random_num = "%06d" % num

        print(random_num)  # 生成随机数,发送用户

        # result = sms.CCP().send_template_sms(mobile, [random_num, constants.SMS_CODE_REDIS_EXPIRES/60], 1)
        #
        # if result != 0:
        #     return jsonify(errno=RET.PARAMERR, errmsg="短信验证无法发送")

        # 验证码保存Redis数据库 -- 注意时间长
        try:
            redis_store.set("smsCode:"+mobile, random_num, constants.SMS_CODE_REDIS_EXPIRES)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="短信验证码无法保存")

        return jsonify(errno=RET.OK, errmsg="发送验证码成功")


# 获取图片验证码
@passport_blue.route("/image_code")
def image_code():
    # 获取图片 GET 方法
    if request.method == 'GET':

        uuid = request.args.get('imageCodeId')

        if not uuid:
            abort(404)

        # 返回三个数据
        image_id, code, image_bin = captcha.generate_captcha()

        if not all([image_id, code, image_bin]):
            abort(404)

        # 保存code 到Redis数据库
        try:
            redis_store.set("imageCode:"+uuid, code)
        except Exception as e:
            current_app.logger.error(e)
            abort(400)

        response = make_response(image_bin)

        response.headers["Content-Type"] = "image/png"

        return response

info/user/__init__.py
from flask import Blueprint

user_blue = Blueprint('users', __name__, url_prefix='/users')

from . import views

info/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock titleBlock %}</title>
    {% block cssBlock %}
    {% endblock cssBlock %}
</head>
<body>

    <div class="header_con">
        <div class="header">
            <a href="{{ url_for("news.index") }}" class="logo fl"><img src="../static/news/images/logo.png" alt="logo"></a>
            {% block navBlock %}
            {% endblock navBlock %}
{#        主页右上角处理#}
            {% if context.user %}
                <div class="user_login fr">
                {% if context.user.avatar_url %}
                    <img src="{{ context.user.avatar_url }}" class="lgin_pic">
                {% else %}
                    <img src="../static/news/images/person01.png" class="lgin_pic">
                {% endif %}

                    <a href="{{ url_for('users.index') }}">{{ context.user.nick_name }}</a>
                    <a href="javascript:;" onclick="logout();">退出</a>
                </div>
            {% else %}
                <div class="user_btns fr">
                    <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="conter_con">
    {% block totalBlock %}

        <ul class="list_con fl">
{#            使用js动态的渲染服务器响应的主页新闻列表数据#}

        </ul>

        <div class="rank_con fr">
        {% block userBlock %}
        {% endblock userBlock %}
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">

                {% for news in context.news %}
                     <li>
                         <span class="{{ loop.index | rank }}">
                             {{ loop.index }}
                         </span>
                         <a href="{{ url_for("news.detail", num_id=news.id) }}">{{ news.title }}</a>
                     </li>
                {% endfor %}
            </ul>
        </div>
    {% block contentBlock %}
    {% endblock contentBlock %}
    {% endblock totalBlock %}
    </div>

    <div class="footer">        
        <div class="footer_links">
            <a href="">关于我们</a>
            <span>|</span>
            <a href="">联系我们</a>
            <span>|</span>
            <a href="">招聘人才</a>
            <span>|</span>
            <a href="">友情链接</a>
        </div>
        <p class="copyright">
            CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
        </p>
    </div>
    
    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>